update c2a and c2v to use cxs for circuit conversion

diff --git a/scripts/c2a b/scripts/c2a
--- a/scripts/c2a
+++ b/scripts/c2a
@@ -6,10 +6,10 @@
 set -e
 
 usage () {
-    echo "C2A: Cryptol to acirc through AND-inverter graphs"
-    echo "Usage: $0 <cryptol-file> <function>"
-    echo "Options:"
-    echo "  -n      skip optimization step"
+    echo "C2A: Cryptol to acirc through AND-inverter graphs" > /dev/stderr
+    echo "Usage: $0 <cryptol-file> <function>" > /dev/stderr
+    echo "Options:" > /dev/stderr
+    echo "  -n      skip optimization step" > /dev/stderr
     exit $1
 }
 
@@ -29,9 +29,16 @@ if [ x$1 = x ] || [ x$2 = x ]; then
     usage 1
 fi
 
+if ! [ -f cxs ]; then
+    echo "[c2a] ERROR: cxs not present! maybe you should run ./build_cxs.sh" >/dev/stderr
+    exit 1
+fi
+cxs=$(readlink -f cxs)
+
 num_test_cases=10
 
 scriptdir=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
+dir=$(pwd)
 
 cryptolfile=$(realpath $1)
 func=$2
@@ -69,6 +76,11 @@ sizes=($(egrep "^$func\\s*:\\s*" $cryptolfile | perl -ne \
 xsize=${sizes[0]}
 ysize=${sizes[1]}
 
+fixed_input=""
+for i in $(seq $xsize $((xsize + ysize - 1))); do
+    fixed_input+=" $i:0"
+done
+
 saw sawcmds.saw > /dev/null
 abc -f abccmds.abc > /dev/null
-perl $scriptdir/bench2circ.pl $func.bench ${3:-arithmetic-circuit} $xsize $ysize
+$cxs read $func.bench -o $dir/$func.c2a.acirc -k "$fixed_input"
diff --git a/scripts/c2v b/scripts/c2v
--- a/scripts/c2v
+++ b/scripts/c2v
@@ -41,9 +41,16 @@ if [ x$1 = x ] || [ x$2 = x ]; then
     usage 1
 fi
 
+if ! [ -f cxs ]; then
+    echo "[c2a] ERROR: cxs not present! maybe you should run ./build_cxs.sh" >/dev/stderr
+    exit 1
+fi
+cxs=$(readlink -f cxs)
+
 cryptolfile=$(realpath $1)
 func=$2
 
+dir=$(pwd)
 tmp=$(mktemp -d)
 cd $tmp
 
@@ -73,12 +80,19 @@ sizes=($(egrep "^$func\\s*:\\s*" $cryptolfile | perl -ne \
 inputsize=${sizes[0]}
 keysize=${sizes[1]}
 
+fixed_input=""
+for i in $(seq $inputsize $((inputsize + keysize - 1))); do
+    fixed_input+=" $i:0"
+done
+
 saw sawcmds.saw > /dev/null
 abc -f abccmds.abc > /dev/null
 yosys yosys.ys > /dev/null
 
 if [ "$opt_binary" ]; then
-    cat $func.out.v
+    cat $func.out.v > $dir/$func.c2v.netlist
 else
-    python $scriptdir/verilog2acirc.py $func.out.v $inputsize $keysize
+    mv $func.out.v $func.netlist
+    $cxs read $func.netlist -o $dir/$func.c2v.acirc -k "$fixed_input"
+    echo "$cxs read $func.netlist -o $dir/$func.c2v.acirc -k \"$fixed_input\"" >/dev/stderr
 fi
